package rules2

import com.ftn.SBZ_2018_Projekat.SBZ_2018_Projekat.dto.MedicationDTO;
import com.ftn.SBZ_2018_Projekat.SBZ_2018_Projekat.model.Patient;
import com.ftn.SBZ_2018_Projekat.SBZ_2018_Projekat.model.Antibiotic;
import com.ftn.SBZ_2018_Projekat.SBZ_2018_Projekat.model.Substance;
import java.util.Set;

rule "Check Allergy"
	no-loop true
	lock-on-active true
	when 
		$m : MedicationDTO($patient : patient, $antibiotics : antibiotics)
		Patient( $allergicToAntibiotics : allergicToAntibiotic, $allergicToSubstances : allergicToSubstance) from $patient
		accumulate(	
			Antibiotic($id : id) from $allergicToAntibiotics and
			$a1 : Antibiotic( $id==id ) from $antibiotics,
			
			$allergicTo1 : collectSet($a1)
		)	
		accumulate(
			$a2 : Antibiotic( $substances : substances ) from $antibiotics and
			Substance($idSubstance : id) from $substances and
			Substance($idSubstance==id) from $allergicToSubstances,
		
			$allergicTo2 : collectSet($a2)
		)
				
	then
			for(Antibiotic a : (Set<Antibiotic>)$allergicTo1){
				$m.getAllergicTo().add(a);
			}
			
			for(Antibiotic a : (Set<Antibiotic>)$allergicTo2){
				$m.getAllergicTo().add(a);
			}
			
			update($m);
end